import React from 'react'
import NextHead from 'next/head'

interface HeadProps {
  title: string
}

const Head: React.FC<HeadProps> = ({ title }) => {
  return (
    <NextHead>
      <title>
        {title}
      </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  )
}

export default Head